/**
 * Money.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * THE RULE: money is always an integer count of fils. Never a decimal, never a
 * float, never a `number` that came from parsing user input directly.
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * Why this file exists at all:
 *
 * In C# you would reach for `decimal`, which stores base-10 fractions exactly.
 * JavaScript has no decimal type — every number is an IEEE-754 double. So
 * `0.1 + 0.2 === 0.30000000000000004`, and money arithmetic accumulates error.
 *
 * Kuwait makes this sharper than most markets: KWD has **three** decimal
 * places, not two. 1 dinar = 1000 fils. A price of "12.500 KWD" is 12500 fils.
 *
 * Get this wrong and nothing breaks loudly. It surfaces months later as gym
 * payouts that are off by a few fils and will not reconcile — the worst
 * possible place to discover a rounding bug.
 */

// ── `declare const` ──
// This declares that a value EXISTS for type-checking purposes without
// actually creating one. No JavaScript is generated by this line at all.
//
// `unique symbol` is a TypeScript type meaning "a one-of-a-kind key that
// nothing else can ever equal". It is used purely as a private label below.
declare const filsBrand: unique symbol;

/**
 * A "branded" type. At runtime this is just a number; at compile time it is a
 * distinct type, so a raw `number` cannot be passed where `Fils` is expected.
 *
 * C# would do this with a readonly struct. TypeScript has no runtime wrapper —
 * this is a pure compile-time trick with zero cost — but it gives you the same
 * protection: you cannot accidentally add a price to a rating.
 */
// ── Reading `number & { readonly [filsBrand]: "Fils" }` ──
//
// `&` is an INTERSECTION: "has everything from the left AND everything from
// the right". So a `Fils` is a number that ALSO carries an invisible marker.
//
// `[filsBrand]` in square brackets is a computed property key — the key is
// whatever the `filsBrand` symbol is, not the literal text "filsBrand".
//
// Because nothing outside this file can produce that symbol, nothing outside
// this file can fabricate a `Fils` except by calling `fils()` below. A plain
// `5` will be rejected where `Fils` is required. At runtime it really is just
// the number 5 — the whole apparatus vanishes when the code is compiled.
export type Fils = number & { readonly [filsBrand]: "Fils" };

/** 1 KWD = 1000 fils. Unusual — most currencies use 100 minor units. */
export const FILS_PER_DINAR = 1000;

// `0 as Fils` is a TYPE ASSERTION: "compiler, trust me, treat this as Fils".
// It is the escape hatch that makes branding possible. Use it sparingly — an
// assertion silences the compiler rather than proving anything.
export const ZERO = 0 as Fils;

// ─────────────────────────────────────────────────────────────── construction

/**
 * The only sanctioned way to create Fils from a raw number.
 * Throws on anything that is not a safe, non-negative integer.
 */
export function fils(value: number): Fils {
  // `Number.isSafeInteger` is stricter than checking for a whole number: it
  // also rejects values so large that JavaScript can no longer represent
  // every integer exactly (beyond about 9 quadrillion).
  if (!Number.isSafeInteger(value)) {
    // TypeError vs RangeError: both are built-in JavaScript error classes.
    // TypeError means "wrong kind of thing", RangeError means "right kind,
    // impossible value". Choosing the accurate one helps whoever reads the log.
    //
    // The backticks make a TEMPLATE LITERAL — a string where `${...}` splices
    // in a value. Equivalent to C#'s $"..." interpolated strings.
    throw new TypeError(`Fils must be a whole number, received: ${value}`);
  }
  if (value < 0) {
    throw new RangeError(`Fils cannot be negative, received: ${value}`);
  }
  return value as Fils;
}

/**
 * Parses a human-written amount such as "12.500", "12.5" or "12".
 *
 * Deliberately string-based: it never routes the value through a float, so
 * there is no rounding to get wrong. This is the correct way to read a price
 * from a form, an API payload, or a CSV import from a gym.
 */
export function parseKwd(input: string): Fils {
  // `.replace(/,/g, "")` strips thousands separators. The `/,/g` is a REGULAR
  // EXPRESSION literal — the pattern sits between slashes, and `g` means
  // "global", i.e. replace every match rather than just the first.
  const trimmed = input.trim().replace(/,/g, "");

  // ── Reading the regular expression `/^(\d+)(?:\.(\d{1,3}))?$/` ──
  //   ^          start of the string
  //   (\d+)      CAPTURE GROUP 1: one or more digits (the dinars)
  //   (?:...)    a group that does NOT capture — used only for grouping
  //     \.       a literal dot (escaped, because a bare `.` means "any char")
  //     (\d{1,3}) CAPTURE GROUP 2: one to three digits (the fils)
  //   ?          the whole non-capturing group is optional
  //   $          end of the string
  //
  // `.exec()` returns an array of matches, or `null` if nothing matched.
  // match[0] is the whole match; match[1] and match[2] are the two groups.
  const match = /^(\d+)(?:\.(\d{1,3}))?$/.exec(trimmed);
  if (!match) {
    throw new TypeError(`Not a valid KWD amount: "${input}"`);
  }

  const dinars = Number(match[1]);
  // "12.5" means 500 fils, not 5 — pad the fractional part to three digits.
  //
  // `??` is the NULLISH COALESCING operator: "use the left side unless it is
  // null or undefined, in which case use the right". Group 2 is optional, so
  // it is `undefined` for an input like "12". Note it differs from `||`,
  // which would also replace an empty string or a 0.
  const fraction = (match[2] ?? "").padEnd(3, "0");

  return fils(dinars * FILS_PER_DINAR + Number(fraction));
}

/**
 * Converts from a decimal number of dinars.
 *
 * Prefer `parseKwd` wherever the value started life as text. This exists for
 * the cases where you genuinely have a number already, and it rounds rather
 * than truncating so that 12.4999999 becomes 12500 rather than 12499.
 */
export function fromDinars(dinars: number): Fils {
  // `Number.isFinite` rejects Infinity and NaN ("not a number"), both of
  // which are ordinary values in JavaScript that arithmetic can produce.
  if (!Number.isFinite(dinars)) {
    throw new TypeError(`Not a finite amount: ${dinars}`);
  }
  return fils(Math.round(dinars * FILS_PER_DINAR));
}

// ───────────────────────────────────────────────────────────────── arithmetic

// Why wrap `a + b` in a function at all? Because `a + b` on two `Fils` values
// produces a plain `number` — TypeScript does not keep the brand through
// arithmetic. Routing it back through `fils()` restores the brand AND
// re-runs the validation, so an overflow or a negative is caught here.
export function add(a: Fils, b: Fils): Fils {
  return fils(a + b);
}

/** Throws rather than returning a negative amount — that is always a bug here. */
export function subtract(a: Fils, b: Fils): Fils {
  return fils(a - b);
}

/** Multiplies by a whole quantity, e.g. three months of the same plan. */
export function multiply(amount: Fils, quantity: number): Fils {
  if (!Number.isSafeInteger(quantity) || quantity < 0) {
    throw new RangeError(`Quantity must be a non-negative whole number: ${quantity}`);
  }
  return fils(amount * quantity);
}

// These four are one-line arrow functions. `(a: Fils): boolean => a === 0`
// means "take a, return whether it equals 0" — the value after `=>` is
// returned automatically, with no `return` keyword needed.
//
// `===` is strict equality: no type coercion. Always prefer it to `==`,
// which converts types first and produces surprises like `"" == 0` being true.
export const isZero = (a: Fils): boolean => a === 0;
// `compare` returns a negative number, zero, or a positive number. That is
// the contract JavaScript's `.sort()` expects from a comparison function.
export const compare = (a: Fils, b: Fils): number => a - b;
// `a >= b ? a : b` is the TERNARY operator: condition ? valueIfTrue : valueIfFalse.
export const max = (a: Fils, b: Fils): Fils => (a >= b ? a : b);
export const min = (a: Fils, b: Fils): Fils => (a <= b ? a : b);

// ──────────────────────────────────────────────────────────── rates and splits

/**
 * Percentages are expressed in **basis points**: whole numbers where
 * 10000 bp = 100%. So a 15% commission is 1500, and 2.5% is 250.
 *
 * Using integers rather than 0.15 keeps rates out of floating-point entirely.
 */
// Unlike `Fils`, this alias is NOT branded — it is just a readable name for
// `number`. A plain number can be passed wherever BasisPoints is expected.
// The name documents intent; it does not enforce it.
export type BasisPoints = number;

export const percentToBasisPoints = (percent: number): BasisPoints =>
  Math.round(percent * 100);

/**
 * Splits a payment between the platform and the gym.
 *
 * The platform's cut is rounded DOWN, and the gym receives the remainder. That
 * means the two parts always sum to exactly the amount the customer paid — no
 * stray fils appears or vanishes — and any rounding difference favours the gym,
 * which is the side you want to err on in a marketplace.
 */
export function splitCommission(
  total: Fils,
  rate: BasisPoints,
  // The return type is an object with two named fields. TypeScript lets you
  // describe a shape inline like this without declaring a separate type.
): { readonly platform: Fils; readonly gym: Fils } {
  // `10_000` uses numeric separators. The underscores are ignored by
  // JavaScript and exist purely so long numbers stay readable.
  if (!Number.isSafeInteger(rate) || rate < 0 || rate > 10_000) {
    throw new RangeError(`Commission must be 0–10000 basis points, received: ${rate}`);
  }
  const platform = fils(Math.floor((total * rate) / 10_000));
  // `{ platform, gym: ... }` again mixes shorthand (`platform`) with an
  // explicit key (`gym:`). Both forms are fine in the same object literal.
  return { platform, gym: subtract(total, platform) };
}

/**
 * Divides an amount into parts by weight, losing nothing.
 *
 * The naive approach — dividing and rounding each part — silently loses or
 * invents fils. This distributes the remainder one fil at a time, so the parts
 * always sum back to the original. Needed for split payouts and for prorating
 * a refund across a partly-used membership.
 *
 *   allocate(fils(1000), [1, 1, 1])  →  [334, 333, 333]
 */
// `readonly number[]` means "an array of numbers that this function promises
// not to modify". `Type[]` is array syntax — the equivalent of C#'s `int[]`.
export function allocate(total: Fils, weights: readonly number[]): readonly Fils[] {
  if (weights.length === 0) {
    throw new RangeError("Cannot allocate across zero parts");
  }
  // `.some(fn)` returns true if the callback returns true for ANY element.
  // Its mirror image is `.every(fn)`, true only when all elements pass.
  if (weights.some((w) => w < 0)) {
    throw new RangeError("Allocation weights cannot be negative");
  }

  // `.reduce(fn, initialValue)` folds an array down to a single value. The
  // callback receives the running total (`sum`) and the current element (`w`),
  // and whatever it returns becomes the running total for the next element.
  // Here: 0 + w1 + w2 + ... — the sum of all weights.
  const totalWeight = weights.reduce((sum, w) => sum + w, 0);
  if (totalWeight <= 0) {
    throw new RangeError("Allocation weights must sum to more than zero");
  }

  // `.map(fn)` builds a NEW array by running the callback on each element.
  // It never modifies the original. This is the workhorse of the codebase —
  // you will see it again in every React component that renders a list.
  const shares = weights.map((w) => Math.floor((total * w) / totalWeight));

  // `let` rather than `const` because this value is reassigned in the loop
  // below. Default to `const`; reach for `let` only when you must reassign.
  let remainder = total - shares.reduce((sum, s) => sum + s, 0);

  // Hand the leftover fils out one at a time, largest weight first.
  //
  // The map pairs each weight with its original index, because `.sort()`
  // would otherwise lose track of where each weight came from. `.sort()`
  // modifies the array in place and takes a comparison function; `b.w - a.w`
  // sorts descending (swap to `a.w - b.w` for ascending).
  const order = weights.map((w, i) => ({ w, i })).sort((a, b) => b.w - a.w);

  // `for...of` iterates over the VALUES of an array (unlike `for...in`,
  // which gives you the keys and is almost never what you want).
  //
  // `const { i } of order` destructures each element, pulling out just the
  // `i` field and ignoring `w`.
  for (const { i } of order) {
    if (remainder <= 0) break;
    // `shares[i] ?? 0` guards against `undefined`. TypeScript cannot prove
    // that index `i` is inside the array, so it types the read as possibly
    // undefined and insists on a fallback.
    shares[i] = (shares[i] ?? 0) + 1;
    remainder -= 1;
  }

  return shares.map((s) => fils(s));
}

// ───────────────────────────────────────────────────────────────── formatting

/**
 * Formats for display. This is the ONLY place fils become a decimal string,
 * and it happens at the very edge of the app — never in storage, never in an
 * API payload, never in a calculation.
 *
 *   formatKwd(fils(12500), "en")  →  "KWD 12.500"
 *   formatKwd(fils(12500), "ar")  →  "‏12.500 د.ك."
 */
// `locale: "ar" | "en" = "ar"` combines two ideas: the type is a union of two
// literal strings (nothing else is accepted), and `= "ar"` makes the
// parameter optional with a default, exactly like a C# default argument.
export function formatKwd(amount: Fils, locale: "ar" | "en" = "ar"): string {
  // Western digits even in Arabic — the norm for Kuwaiti apps.
  //
  // `ar-KW-u-nu-latn` is a BCP-47 language tag: Arabic, Kuwait region, with a
  // Unicode extension (`-u-`) requesting the Latin numbering system
  // (`nu-latn`). Without it you would get Arabic-Indic digits: ١٢.٥٠٠
  const tag = locale === "ar" ? "ar-KW-u-nu-latn" : "en-KW";

  // `Intl` is built into JavaScript — no library needed. It handles currency
  // symbols, digit grouping, and where the symbol sits relative to the number,
  // all per-locale. Reimplementing this by hand is a classic mistake.
  return new Intl.NumberFormat(tag, {
    style: "currency",
    currency: "KWD", // Intl already knows KWD has three decimal places.
  }).format(amount / FILS_PER_DINAR);
}

/** Bare number, no currency symbol — for input fields and CSV export. */
export function toDecimalString(amount: Fils): string {
  const dinars = Math.floor(amount / FILS_PER_DINAR);
  // `%` is the remainder operator: 12500 % 1000 = 500.
  const remainder = amount % FILS_PER_DINAR;
  // `.padStart(3, "0")` left-pads to three characters, so 5 fils renders as
  // "005" and the result reads "12.005" rather than the wrong "12.5".
  return `${dinars}.${String(remainder).padStart(3, "0")}`;
}
